name: Build and Test app

on:
  push:
    branches:
      - '**'

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Static Tests
        run: npm run test:static
      - name: Run Tests
        run: npm test
      - name: Build frontend
        run: npm run build

  build-django:
    runs-on: ubuntu-latest
    needs: build-frontend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install -r requirements.txt
      - name: Run Static Tests
        run: |
          pre-commit run --all-files
      - name: Run Tests
        run: |
          mv .env.sample .env
          python manage.py test
